version: '3.3'

services:

  otus-jupyter-notebook:
    image:    jupyter/datascience-notebook
    volumes:
      - ".:/home/jovyan/work"
    container_name: otus-jupyter-notebook
    ports:
    - 8888:8888

networks:
  shared:
    driver: bridge
