version: '3.3'

services:

  otus_mysql:
    image: mysql:5.7
    container_name: otus_mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --max_allowed_packet=32M
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
       - "./db/mysql:/var/lib/mysql"
    networks:
      - shared
    ports:
      - 3308:3306

  otus_stackoverflow:
    build: .
    container_name: otus_stackoverflow
    restart: always
    volumes:
      - ".:/usr/src/app"
    environment:
      DB_USERNAME: ${MYSQL_USERNAME}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_PORT: ${MYSQL_PORT}
      DB_HOST: ${MYSQL_HOST}
      DB_DATABASE: ${DB_DATABASE}
    networks:
      - shared
    depends_on:
      - otus_mysql
    ports:
      - 8000:8000

networks:
  shared:
    driver: bridge
