version: '3.3'

services:

  otus-mysql:
    image: mysql
    container_name: otus-mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --max_allowed_packet=32M
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
       - "./db/mysql:/var/lib/mysql"
    networks:
      - shared
    ports:
      - 127.0.0.1:3308:3308

  otus_stackoverflow:
    build: ./
    container_name: otus_stackoverflow
#    restart: always
    command: bash
    volumes:
      - "./app:/usr/src/app"
    networks:
      - shared
    depends_on:
      - otus-mysql
    ports:
      - 127.0.0.1:6000:8000

networks:
  shared:
    driver: bridge
